### ISSUE TITLE
测试了图片路径不支持中文，protobuf会报错

### ISSUE THREAD

**Issue by futureflsl** [swigger/wechat-ocr#10]
这个protobuf源码来自哪个作者，能否提供支持一下中文路径

**Comment by swigger** [comment]
其实是支持的，但是你传入的图片路径必须utf-8编码。
protobuf 是google的产品。

我现在更新了一下代码，加入了一个编码检查，如果传入的路径不是utf-8的，就会转成utf-8的。
你可以再试试，当然最保险的做法是你传入就是utf-8

**Comment by futureflsl** [comment]
> 其实是支持的，但是你传入的图片路径必须utf-8编码。 protobuf 是google的产品。
> 
> 我现在更新了一下代码，加入了一个编码检查，如果传入的路径不是utf-8的，就会转成utf-8的。 你可以再试试，当然最保险的做法是你传入就是utf-8

牛掰，我已经改了
