### ISSUE TITLE
请问可以提供一个32位的pyd吗

### ISSUE THREAD

**Issue by znahovo** [swigger/wechat-ocr#13]
作者您好，请问您可以release的时候再提供一个python的32位pyd文件吗

**Comment by swigger** [comment]
我有点好奇啥年代了还要32位，就算是穷学生用10年前的CPU也是完全支持64位的

**Comment by znahovo** [comment]
后来我看了一下，32位的wechat貌似没有自带wechatocr 所以应该也用不了，这个想给其他人用的，感谢回复
