### ISSUE TITLE
大佬好，改了转义字符，重新编译，C#调用报内存损坏

### ISSUE THREAD

**Issue by net10010** [swigger/wechat-ocr#18]
需要重新编译的原因是：
![image](https://github.com/user-attachments/assets/14dae628-81cc-4aea-b59e-05ffaa40265d)
这部分拼json时，假如字符串中存在转义字符，得到的结果就没办法解析了。

安装了C++环境，好不容易改完了，结果编译之后就不能正常运行。不确定大佬的编译配置是什么，试了几种还是不行。

附增加的字符串转义方法，等大佬翻牌：
string escape_json_string(const string& input) {
	string output;
	output.reserve(input.length() * 2); // 预分配空间

	for (char c : input) {
		switch (c) {
		case '\"': output += "\\\""; break;
		case '\\': output += "\\\\"; break;
		case '\b': output += "\\b"; break;
		case '\f': output += "\\f"; break;
		case '\n': output += "\\n"; break;
		case '\r': output += "\\r"; break;
		case '\t': output += "\\t"; break;
		default:
			if ('\x00' <= c && c <= '\x1f') {
				char buf[8];
				snprintf(buf, sizeof(buf), "\\u%04x", c);
				output += buf;
			}
			else {
				output += c;
			}
		}
	}
	return output;
}

**Comment by net10010** [comment]
尝试把改动的代码恢复，用Release编译，调用也是报错。
但是用DEBUG模式编译，调用是正常的。
不过DEBUG模式编译的DLL文件有1.几MB

**Comment by swigger** [comment]
可以把报错的详细错误信息发出来。特别是在release版直接调试的情况下，callstack相关信息发出来

**Comment by net10010** [comment]
大佬好：

C# 调用代码：
[DllImport("wcocr.dll", CallingConvention = CallingConvention.Cdecl)]
static extern bool wechat_ocr(
    [MarshalAs(UnmanagedType.LPWStr)] string ocr_exe,
    [MarshalAs(UnmanagedType.LPWStr)] string wechat_dir,
    [MarshalAs(UnmanagedType.LPStr)] string imgfn,
    SetResultDelegate set_res);

bool success = wechat_ocr(strOcrFile, strAppPath, strImageFile, setRes);

报错信息：
未经处理的异常: Systen AccessViolationException:尝试读取或写入受保护的内存。这通常指示其他内存已损坏。
在TencentLocalOCR.Program wechat_ocr(String ocr_exe, String wechat_dir, String imgfn, SetResultDelegate set_res)


用DEBUG模式编译，运行是正常的，只是DLL文件比较大，1M多。
用Release模式编译的运行就是上边的效果，生成的DLL 111kb，跟您之前发出来的差不多。

应该是编译选项跟您的不一样，对C++不太了解。尝试改了几个编译参数，还是没搞定。

希望大佬把上边的字符串转义方法加下，按您的配置生个Release的DLL。

**Comment by swigger** [comment]
已经修改代码重新编译，你可以试试demo-4

**Comment by net10010** [comment]
可以了，转义字符能正常返回并解析，感谢大佬！

**Comment by net10010** [comment]
问题关闭！
