### ISSUE TITLE
 DLL load failed while importing wcocr: 找不到指定的模块

### ISSUE THREAD

**Issue by cumthxy** [swigger/wechat-ocr#2]
DLL load failed while importing wcocr: 找不到指定的模块

**Comment by swigger** [comment]
你自己好好检查 一下：
1。 python用3.10 64位
2。py文件里的路径已经设置正确，自己print出来检查是否存在。
3。vc redist package 2015-20222已经安装。（一般机器都有，很多程序会帮你装，实在没有就去网上下）

**Comment by lonlonago** [comment]
可以分享一下dll吗  demo 里面没有dll , 不知道怎么built这个

**Comment by xinye0123** [comment]
我也是这样，是不是除了pyd，还需dll？能否一起打包

**Comment by xinye0123** [comment]
pyd 不就是 dll吗 怎么会提示找不到呢

**Comment by swigger** [comment]
* 不行就试试运行 `regsvr32 wcocr.pyd` 看看报什么错，也许就明白了。
* 再不行下载文件 [Dependencies_x64_Release.zip](https://github.com/lucasg/Dependencies/releases/download/v1.11.1/Dependencies_x64_Release.zip)）
运行 `DependenciesGui.exe` 检查一下 `wcocr.pyd` ，看看缺什么。
PS: 你的微信目录跟我的可能不一样，你不会连 `test.py` 中的路径都没改就试着运行吧？

* 还有一个终级解决办法，适合检查“找不到文件”这一错误类别的所有场景。那就是下载一个 `process monitor`，看看它尝试打开哪个文件但是没有成功。

以上3种方法从易到难，从不太有效到强力有效，都是“**渔**”不是**鱼**，请自行学习研究。

**Comment by ef6** [comment]
查了一下缺这三个dll。

![image](https://github.com/swigger/wechat-ocr/assets/17763501/c3c78cdf-d8b9-4360-b469-d20a4d813309)

然而我的python版本是3.12，版本不对，还是必须安装3.10版本的python
> ImportError: Module use of python310.dll conflicts with this version of Python.

这么着也不是个事，还是考虑写个纯python库比较好

**Comment by swigger** [comment]
mmmojo是微信目录的，如果你的微信目录配置正确，且安装的是64位，就有这个。zlib我没有用到，可能是你的环境别的地方带来的，这个dll很常见，我电脑上不同的软件一共安装了15份（有些是32位的，腾讯的都是32位）。python版本3.10是编译时确定的，必须用3.10，我前面已经说过了。需要3.12的必须用py312环境重新编译
