### ISSUE TITLE
demo5编译出的pyd有问题，调用ocr时报错

### ISSUE THREAD

**Issue by Yayhub** [swigger/wechat-ocr#27]
pyd调用在ocr时报错wechatocr实例化失败，demo5版本

**Comment by swigger** [comment]
你可能需要先学会如何正确的报告错误。也可以认真看看错误报告文本和使用说明。自己先研究一下一些基础问题。

**Comment by Yayhub** [comment]
感谢回复！找到问题了，集显和虚拟机用不了wxocr的离线识别

**Comment by Yayhub** [comment]
感谢回复！找到问题了，集显和虚拟机用不了wxocr的离线识别
