### ISSUE TITLE
Can't open the file“x64\libprotobuf-lited.lib”

### ISSUE THREAD

**Issue by GenuineBoss** [swigger/wechat-ocr#5]
dear swiger,
one error "Can't open the file“x64\libprotobuf-lited.lib”" pompted while  the code being compiled on visual studio 2022 v143( C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519) ,windows SDK version:10.0.22621.0,C++language std:ISO C++20 标准(/std:c++20),C language std:ISO C17 (2018)standard(/std:c17) , I'm wondering the file is missing, could you please help to check ,the error and configuration settings attached for your reference, thanks !   Email: angely.dong@outlook.com
[error ecountered.zip](https://github.com/swigger/wechat-ocr/files/15228185/error.ecountered.zip)

**Comment by swigger** [comment]
libraries were forgotten to push to github.
and now they're there.
