### ISSUE TITLE
这个项目是不是不行了，C++例子跑不起来

### ISSUE THREAD

**Issue by futureflsl** [swigger/wechat-ocr#9]
运行直接闪退，发现报错在CWeChatOCR ocr(wechatocr_path, wechat_path);这句上，没有任何提示，传的路径均是对的

**Comment by swigger** [comment]
不要一惊一乍的，我试过了可以运行。
你确认了你的微信是64位的吗？

**Comment by futureflsl** [comment]
> 不要一惊一乍的，我试过了可以运行。 你确认了你的微信是64位的吗？
试了，原来用vs2022可以，我先前用vs2019不行
